[economy]
base = "copper"
display = "compact"

[economy.starting_wealth]
player = 50

[economy.currencies.copper]
name = "Copper"
symbol = "c"
value = 1

[economy.currencies.silver]
name = "Silver"
symbol = "s"
value = 10

[economy.currencies.gold]
name = "Gold"
symbol = "g"
value = 100
