; Generated by `cargo xtask recipe-language`; do not edit.
(comment) @comment
(string) @string
(color) @string.special
(number) @number
(boolean) @boolean
(declaration kind: (_) @keyword)
(declaration name: (identifier) @type)
(block kind: (block_kind) @keyword)
(block name: (identifier) @variable)
(assignment name: (property) @property)
(call function: (identifier) @function)
(member property: (identifier) @property)
((identifier) @constant (#match? @constant "^[A-Z]"))
(operator) @operator
["(" ")" "," "."] @punctuation.bracket
