use serde::Deserialize;
use serde_json::json;
use std::{
    env, fs,
    path::{Path, PathBuf},
};

const GENERATED_NOTICE: &str = "Generated by `cargo xtask recipe-language`; do not edit.";

#[derive(Debug, Deserialize)]
struct LanguageDefinition {
    name: String,
    language_id: String,
    scope: String,
    extensions: Vec<String>,
    line_comment: String,
    declarations: Vec<String>,
    booleans: Vec<String>,
}

struct Artifact {
    path: &'static str,
    contents: String,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let mut arguments = env::args().skip(1);
    let Some(command) = arguments.next() else {
        return Err("usage: cargo xtask recipe-language [--check]".into());
    };
    if command != "recipe-language" {
        return Err(format!("unknown xtask '{command}'"));
    }
    let check = match arguments.next().as_deref() {
        None => false,
        Some("--check") => true,
        Some(argument) => return Err(format!("unknown argument '{argument}'")),
    };
    if let Some(argument) = arguments.next() {
        return Err(format!("unexpected argument '{argument}'"));
    }

    let root = workspace_root();
    let source_path = root.join("crates/procedural_recipes/language/highlighting.toml");
    let source = fs::read_to_string(&source_path)
        .map_err(|error| format!("cannot read '{}': {error}", source_path.display()))?;
    let definition: LanguageDefinition = toml::from_str(&source)
        .map_err(|error| format!("invalid '{}': {error}", source_path.display()))?;
    validate_definition(&definition)?;

    let artifacts = generate_artifacts(&definition)?;
    let mut stale = Vec::new();
    for artifact in artifacts {
        let path = root.join(artifact.path);
        if check {
            if fs::read_to_string(&path).ok().as_deref() != Some(&artifact.contents) {
                stale.push(artifact.path);
            }
        } else {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("cannot create '{}': {error}", parent.display()))?;
            }
            fs::write(&path, artifact.contents)
                .map_err(|error| format!("cannot write '{}': {error}", path.display()))?;
            println!("generated {}", artifact.path);
        }
    }

    if stale.is_empty() {
        if check {
            println!("Recipe language artifacts are current");
        }
        Ok(())
    } else {
        Err(format!(
            "generated Recipe language artifacts are stale:\n  {}\nrun `cargo xtask recipe-language`",
            stale.join("\n  ")
        ))
    }
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask must live directly under the workspace root")
        .to_path_buf()
}

fn validate_definition(definition: &LanguageDefinition) -> Result<(), String> {
    if definition.declarations.is_empty() {
        return Err("Recipe highlighting needs at least one declaration".into());
    }
    if definition.extensions.is_empty() {
        return Err("Recipe highlighting needs at least one extension".into());
    }
    for word in definition.declarations.iter().chain(&definition.booleans) {
        if !word
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_')
        {
            return Err(format!("'{word}' is not a safe highlighting word"));
        }
    }
    Ok(())
}

fn generate_artifacts(definition: &LanguageDefinition) -> Result<Vec<Artifact>, String> {
    Ok(vec![
        Artifact {
            path: "creator/embedded/parser/recipe.sublime-syntax",
            contents: generate_sublime(definition),
        },
        Artifact {
            path: "docs/src/prism-recipe.js",
            contents: generate_prism(definition),
        },
        Artifact {
            path: "editors/vscode-eldiron-recipe/syntaxes/eldiron-recipe.tmLanguage.json",
            contents: generate_textmate(definition)?,
        },
        Artifact {
            path: "editors/vscode-eldiron-recipe/package.json",
            contents: generate_vscode_package(definition)?,
        },
        Artifact {
            path: "editors/vscode-eldiron-recipe/language-configuration.json",
            contents: generate_vscode_configuration(definition)?,
        },
        Artifact {
            path: "editors/tree-sitter-eldiron-recipe/grammar.js",
            contents: generate_tree_sitter_grammar(definition),
        },
        Artifact {
            path: "editors/tree-sitter-eldiron-recipe/package.json",
            contents: generate_tree_sitter_package(definition)?,
        },
        Artifact {
            path: "editors/tree-sitter-eldiron-recipe/queries/highlights.scm",
            contents: generate_tree_sitter_highlights(),
        },
        Artifact {
            path: "editors/zed-eldiron-recipe/languages/eldiron-recipe/config.toml",
            contents: generate_zed_configuration(definition),
        },
        Artifact {
            path: "editors/zed-eldiron-recipe/languages/eldiron-recipe/highlights.scm",
            contents: generate_tree_sitter_highlights(),
        },
    ])
}

fn alternatives(words: &[String]) -> String {
    let mut words = words.to_vec();
    words.sort_by_key(|word| std::cmp::Reverse(word.len()));
    words.join("|")
}

fn regex_escape(text: &str) -> String {
    text.chars()
        .flat_map(|character| {
            if "\\.^$|?*+()[]{}".contains(character) {
                vec!['\\', character]
            } else {
                vec![character]
            }
        })
        .collect()
}

fn generate_sublime(definition: &LanguageDefinition) -> String {
    let declarations = alternatives(&definition.declarations);
    let booleans = alternatives(&definition.booleans);
    let comment = regex_escape(&definition.line_comment);
    format!(
        "%YAML 1.2\n---\n# {GENERATED_NOTICE}\nname: {}\nfile_extensions:\n{}scope: {}\n\ncontexts:\n  main:\n    - match: '{comment}.*$'\n      scope: comment.line.double-slash.eldiron-recipe\n    - match: '\"'\n      scope: punctuation.definition.string.begin.eldiron-recipe\n      push:\n        - meta_scope: string.quoted.double.eldiron-recipe\n        - match: '\"'\n          scope: punctuation.definition.string.end.eldiron-recipe\n          pop: true\n        - match: '\\\\.'\n          scope: constant.character.escape.eldiron-recipe\n    - match: '#[0-9A-Fa-f]{{6}}(?:[0-9A-Fa-f]{{2}})?\\b'\n      scope: constant.other.color.eldiron-recipe\n    - match: '^\\s*({declarations})\\b(?:\\s+([A-Za-z_][A-Za-z0-9_-]*))?'\n      captures:\n        1: keyword.declaration.eldiron-recipe\n        2: entity.name.type.eldiron-recipe\n    - match: '^\\s*([A-Z][A-Za-z0-9_]*)(?:\\s+([A-Za-z_][A-Za-z0-9_-]*))?(?=\\s*(?:{comment}.*)?$)'\n      captures:\n        1: support.type.block.eldiron-recipe\n        2: entity.name.label.eldiron-recipe\n    - match: '^\\s*([a-z_][a-z0-9_]*)\\s*(=)'\n      captures:\n        1: variable.other.property.eldiron-recipe\n        2: keyword.operator.assignment.eldiron-recipe\n    - match: '\\b[A-Z][A-Za-z0-9_]*(?=\\s*\\()'\n      scope: support.function.eldiron-recipe\n    - match: '\\b(?:{booleans})\\b'\n      scope: constant.language.eldiron-recipe\n    - match: '-?(?:\\b\\d+(?:\\.\\d+)?|\\.\\d+)(?:[eE][+-]?\\d+)?\\b'\n      scope: constant.numeric.eldiron-recipe\n    - match: '(?<=\\.)[A-Za-z_][A-Za-z0-9_]*\\b'\n      scope: variable.other.member.eldiron-recipe\n    - match: '\\b[A-Z][A-Za-z0-9_]*\\b'\n      scope: constant.other.eldiron-recipe\n    - match: '==|!=|<=|>=|[=+\\-*/<>]'\n      scope: keyword.operator.eldiron-recipe\n    - match: '[(),.]'\n      scope: punctuation.eldiron-recipe\n",
        definition.name,
        definition
            .extensions
            .iter()
            .map(|extension| format!("  - {extension}\n"))
            .collect::<String>(),
        definition.scope,
    )
}

fn generate_prism(definition: &LanguageDefinition) -> String {
    let declarations = alternatives(&definition.declarations);
    let booleans = alternatives(&definition.booleans);
    let comment = regex_escape(&definition.line_comment).replace('/', "\\/");
    format!(
        "// {GENERATED_NOTICE}\nexport default function loadRecipe(Prism) {{\n  Prism.languages[\"{}\"] = {{\n    comment: {{ pattern: /{comment}.*/, greedy: true }},\n    string: {{ pattern: /\"(?:\\\\.|[^\"\\\\])*\"/, greedy: true }},\n    color: {{ pattern: /#[0-9A-Fa-f]{{6}}(?:[0-9A-Fa-f]{{2}})?\\b/, alias: \"constant\" }},\n    declaration: {{\n      pattern: /(^\\s*)(?:{declarations})(?=\\s|$)/m,\n      lookbehind: true,\n      alias: \"keyword\",\n    }},\n    block: {{\n      pattern: /(^\\s*)[A-Z][A-Za-z0-9_]*(?=(?:\\s+[A-Za-z_][A-Za-z0-9_-]*)?\\s*(?:{comment}.*)?$)/m,\n      lookbehind: true,\n      alias: \"class-name\",\n    }},\n    property: {{\n      pattern: /(^\\s*)[a-z_][a-z0-9_]*(?=\\s*=)/m,\n      lookbehind: true,\n    }},\n    function: /\\b[A-Z][A-Za-z0-9_]*(?=\\s*\\()/,\n    boolean: {{ pattern: /\\b(?:{booleans})\\b/, alias: \"constant\" }},\n    number: /-?(?:\\b\\d+(?:\\.\\d+)?|\\.\\d+)(?:[eE][+-]?\\d+)?\\b/,\n    member: {{ pattern: /(\\.)[A-Za-z_][A-Za-z0-9_]*/, lookbehind: true, alias: \"property\" }},\n    constant: /\\b[A-Z][A-Za-z0-9_]*\\b/,\n    operator: /==|!=|<=|>=|[=+\\-*/<>]/,\n    punctuation: /[(),.]/,\n  }};\n  Prism.languages.recipe = Prism.languages[\"{}\"];\n}}\n",
        definition.language_id, definition.language_id,
    )
}

fn generate_textmate(definition: &LanguageDefinition) -> Result<String, String> {
    let declarations = alternatives(&definition.declarations);
    let booleans = alternatives(&definition.booleans);
    let comment = regex_escape(&definition.line_comment);
    pretty_json(json!({
        "$generated": GENERATED_NOTICE,
        "name": definition.name,
        "scopeName": definition.scope,
        "fileTypes": definition.extensions,
        "patterns": [
            { "name": "comment.line.double-slash.eldiron-recipe", "match": format!("{comment}.*$") },
            { "name": "string.quoted.double.eldiron-recipe", "begin": "\"", "end": "\"", "patterns": [
                { "name": "constant.character.escape.eldiron-recipe", "match": "\\\\." }
            ]},
            { "name": "constant.other.color.eldiron-recipe", "match": "#[0-9A-Fa-f]{6}(?:[0-9A-Fa-f]{2})?\\b" },
            {
                "match": format!("^\\s*({declarations})\\b(?:\\s+([A-Za-z_][A-Za-z0-9_-]*))?"),
                "captures": {
                    "1": { "name": "keyword.declaration.eldiron-recipe" },
                    "2": { "name": "entity.name.type.eldiron-recipe" }
                }
            },
            {
                "match": format!("^\\s*([A-Z][A-Za-z0-9_]*)(?:\\s+([A-Za-z_][A-Za-z0-9_-]*))?(?=\\s*(?:{comment}.*)?$)"),
                "captures": {
                    "1": { "name": "support.type.block.eldiron-recipe" },
                    "2": { "name": "entity.name.label.eldiron-recipe" }
                }
            },
            {
                "match": "^\\s*([a-z_][a-z0-9_]*)\\s*(=)",
                "captures": {
                    "1": { "name": "variable.other.property.eldiron-recipe" },
                    "2": { "name": "keyword.operator.assignment.eldiron-recipe" }
                }
            },
            { "name": "support.function.eldiron-recipe", "match": "\\b[A-Z][A-Za-z0-9_]*(?=\\s*\\()" },
            { "name": "constant.language.eldiron-recipe", "match": format!("\\b(?:{booleans})\\b") },
            { "name": "constant.numeric.eldiron-recipe", "match": "-?(?:\\b\\d+(?:\\.\\d+)?|\\.\\d+)(?:[eE][+-]?\\d+)?\\b" },
            { "name": "variable.other.member.eldiron-recipe", "match": "(?<=\\.)[A-Za-z_][A-Za-z0-9_]*\\b" },
            { "name": "constant.other.eldiron-recipe", "match": "\\b[A-Z][A-Za-z0-9_]*\\b" },
            { "name": "keyword.operator.eldiron-recipe", "match": "==|!=|<=|>=|[=+\\-*/<>]" },
            { "name": "punctuation.eldiron-recipe", "match": "[(),.]" }
        ]
    }))
}

fn generate_vscode_package(definition: &LanguageDefinition) -> Result<String, String> {
    pretty_json(json!({
        "$generated": GENERATED_NOTICE,
        "name": "eldiron-recipe-language",
        "displayName": definition.name,
        "description": "Syntax highlighting for Eldiron procedural Recipe files.",
        "version": "0.0.1",
        "private": true,
        "publisher": "eldiron",
        "engines": { "vscode": "^1.85.0" },
        "categories": ["Programming Languages"],
        "contributes": {
            "languages": [{
                "id": definition.language_id,
                "aliases": [definition.name, "Recipe"],
                "extensions": definition.extensions.iter().map(|extension| format!(".{extension}")).collect::<Vec<_>>(),
                "configuration": "./language-configuration.json"
            }],
            "grammars": [{
                "language": definition.language_id,
                "scopeName": definition.scope,
                "path": "./syntaxes/eldiron-recipe.tmLanguage.json"
            }]
        }
    }))
}

fn generate_vscode_configuration(definition: &LanguageDefinition) -> Result<String, String> {
    pretty_json(json!({
        "$generated": GENERATED_NOTICE,
        "comments": { "lineComment": definition.line_comment },
        "brackets": [["(", ")"]],
        "autoClosingPairs": [
            { "open": "\"", "close": "\"", "notIn": ["string", "comment"] },
            { "open": "(", "close": ")" }
        ],
        "surroundingPairs": [["\"", "\""], ["(", ")"]],
        "indentationRules": {
            "increaseIndentPattern": "^\\s*(?:[A-Z][A-Za-z0-9_]*)(?:\\s+[A-Za-z_][A-Za-z0-9_-]*)?\\s*$",
            "decreaseIndentPattern": "^$"
        }
    }))
}

fn generate_tree_sitter_grammar(definition: &LanguageDefinition) -> String {
    let declarations = definition
        .declarations
        .iter()
        .map(|word| format!("\"{word}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let booleans = definition
        .booleans
        .iter()
        .map(|word| format!("\"{word}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let line_comment = serde_json::to_string(&definition.line_comment)
        .expect("a TOML string must serialize as JSON");
    format!(
        "// {GENERATED_NOTICE}\nmodule.exports = grammar({{\n  name: \"eldiron_recipe\",\n  extras: ($) => [/[ \\t]/],\n  word: ($) => $.identifier,\n  rules: {{\n    source_file: ($) => repeat(choice($.declaration, $.assignment, $.block, $.comment, $._newline)),\n    declaration: ($) => seq(field(\"kind\", choice({declarations})), optional(field(\"name\", $.identifier)), optional($.comment), optional($._newline)),\n    assignment: ($) => seq(field(\"name\", $.property), \"=\", field(\"value\", $.expression), optional($.comment), optional($._newline)),\n    block: ($) => seq(field(\"kind\", $.block_kind), optional(field(\"name\", $.identifier)), optional($.comment), optional($._newline)),\n    expression: ($) => prec.left(seq($._primary, repeat(seq($.operator, $._primary)))),\n    _primary: ($) => choice($.call, $.member, $.string, $.color, $.number, $.boolean, $.identifier, $.parenthesized_expression),\n    parenthesized_expression: ($) => seq(\"(\", $.expression, \")\"),\n    call: ($) => seq(field(\"function\", $.identifier), \"(\", optional(seq($.expression, repeat(seq(\",\", $.expression)))), \")\"),\n    member: ($) => prec.left(seq(field(\"object\", $.identifier), repeat1(seq(\".\", field(\"property\", $.identifier))))),\n    comment: ($) => token(seq({line_comment}, /.*/)),\n    string: ($) => token(seq(\"\\\"\", repeat(choice(/[^\"\\\\\\n]/, /\\\\./)), \"\\\"\")),\n    color: ($) => token(/#[0-9A-Fa-f]{{6}}([0-9A-Fa-f]{{2}})?/),\n    number: ($) => token(/-?([0-9]+(\\.[0-9]+)?|\\.[0-9]+)([eE][+-]?[0-9]+)?/),\n    boolean: ($) => choice({booleans}),\n    property: ($) => /[a-z_][a-z0-9_]*/,\n    block_kind: ($) => /[A-Z][A-Za-z0-9_]*/,\n    identifier: ($) => /[A-Za-z_][A-Za-z0-9_-]*/,\n    operator: ($) => choice(\"==\", \"!=\", \"<=\", \">=\", \"+\", \"-\", \"*\", \"/\", \"<\", \">\"),\n    _newline: ($) => /\\r?\\n/,\n  }},\n}});\n"
    )
}

fn generate_tree_sitter_package(definition: &LanguageDefinition) -> Result<String, String> {
    pretty_json(json!({
        "$generated": GENERATED_NOTICE,
        "name": "tree-sitter-eldiron-recipe",
        "version": "0.0.1",
        "private": true,
        "description": format!("Unpublished Tree-sitter grammar scaffold for {}", definition.name),
        "main": "bindings/node",
        "keywords": ["tree-sitter", "eldiron", "recipe"],
        "license": "MIT",
        "dependencies": { "node-addon-api": "^8.0.0", "node-gyp-build": "^4.8.0" },
        "devDependencies": { "tree-sitter-cli": "^0.25.0" },
        "tree-sitter": [{ "scope": definition.scope, "file-types": definition.extensions }]
    }))
}

fn generate_tree_sitter_highlights() -> String {
    format!(
        "; {GENERATED_NOTICE}\n(comment) @comment\n(string) @string\n(color) @string.special\n(number) @number\n(boolean) @boolean\n(declaration kind: (_) @keyword)\n(declaration name: (identifier) @type)\n(block kind: (block_kind) @keyword)\n(block name: (identifier) @variable)\n(assignment name: (property) @property)\n(call function: (identifier) @function)\n(member property: (identifier) @property)\n((identifier) @constant (#match? @constant \"^[A-Z]\"))\n(operator) @operator\n[\"(\" \")\" \",\" \".\"] @punctuation.bracket\n"
    )
}

fn generate_zed_configuration(definition: &LanguageDefinition) -> String {
    format!(
        "# {GENERATED_NOTICE}\nname = \"{}\"\ngrammar = \"eldiron_recipe\"\npath_suffixes = [{}]\nline_comments = [\"{} \" ]\ntab_size = 2\nhard_tabs = false\n",
        definition.name,
        definition
            .extensions
            .iter()
            .map(|extension| format!("\"{extension}\""))
            .collect::<Vec<_>>()
            .join(", "),
        definition.line_comment,
    )
}

fn pretty_json(value: serde_json::Value) -> Result<String, String> {
    serde_json::to_string_pretty(&value)
        .map(|json| format!("{json}\n"))
        .map_err(|error| error.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn definition() -> LanguageDefinition {
        toml::from_str(include_str!(
            "../../crates/procedural_recipes/language/highlighting.toml"
        ))
        .unwrap()
    }

    #[test]
    fn every_target_is_generated_from_the_same_declarations() {
        let definition = definition();
        let artifacts = generate_artifacts(&definition).unwrap();
        for declaration in &definition.declarations {
            for artifact in &artifacts {
                if artifact.path.ends_with("language-configuration.json")
                    || artifact.path.ends_with("config.toml")
                    || artifact.path.ends_with("highlights.scm")
                    || artifact.path.ends_with("package.json")
                {
                    continue;
                }
                assert!(
                    artifact.contents.contains(declaration),
                    "{} is missing {declaration}",
                    artifact.path
                );
            }
        }
    }

    #[test]
    fn generated_zed_configuration_is_valid_toml() {
        toml::from_str::<toml::Value>(&generate_zed_configuration(&definition())).unwrap();
    }
}
